site_name: 'TINKOFF INVEST API'
docs_dir: docs
repo_url: https://github.com/Tinkoff/investAPI
theme:
  name: material
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/

nav:
- Начало работы: index.md
- Введение:
  - "Протокол взаимодействия": grpc.md
  - "Лимитная политика": limits.md
  - "Токен доступа": token.md
  - "Идентификация торговых инструментов": faq_identification.md
  - "Нестандартные типы данных": faq_custom_types.md
  - "Алгоритмический трейдинг": algorithmic_trading.md
  - "Индикаторы технического анализа": tech_indicators.md
  - "Торговые площадки и режимы торгов": markets.md
  - "Порядок работы с историческими данными": load_history.md
  - "Работа с торговыми поручениями": faq_orders.md
  - "Квалифицированный инвестор": accredited_investor.md
- FAQ:
  - Глоссарий: glossary.md
  - "Часто задаваемые вопросы": faq.md
  - "Правила обработки корпоративных действий": faq_corp_action.md
- Сервис аккаунтов:
  - Описание: head-users.md
  - Методы: users.md
- Сервис инструментов: 
  - Описание: head-instruments.md
  - Методы: instruments.md
- Сервис торговых поручений:
  - Описание: head-orders.md
  - Методы: orders.md
- Сервис операций:
  - Описание: head-operations.md
  - Методы: operations.md
- Сервис котировок:
  - Описание: head-marketdata.md
  - Методы: marketdata.md
- Сервис стоп-заявок:
  - Описание: head-stoporders.md
  - Методы: stoporders.md
- Песочница:
  - Описание: head-sandbox.md
  - Методы: sandbox.md
- Коды ошибок: errors.md
